insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('National Observatory of Athens', 'NOA', '11810', 'Athens', 'Nymphs Hill', '1', 'Research center');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('National Network of Research and Technology', 'GRNET', '11523', 'Athens', 'Kifissias', '7', 'Research center');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Hellenic Centre for Marine Research', 'HCMR', '19013', 'Anavyssos', 'Athens Sounio avenue', '47', 'Research center');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Foundation for research and technology', 'FORTH', '70013', 'Heraklion', 'N.Plastira', '18', 'Research center');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Academy of Athens', 'AOA', '10679', 'Athens', 'Panepistimiou', '28', 'Research center');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Demokritos, National Centre for Scientific Research', 'NCSR', '15341', 'Athens', 'Neapoleos and Patriarxou Grhgoriou', '27', 'Research center');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Centre for Research and Technology Hellas', 'CERTH', '15125', 'Athens', 'Aigialias', '52', 'Research center');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Biomedical Sciences Research Center "Alexander Fleming"', 'BSRC', '16672', 'Vari', 'Fleming', '34', 'Research center');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Centre of Planning and Economic Research', 'KEPE', '10672', 'Athens', 'Amerikis', '11', 'Research center');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('National Hellenic Research Foundation', 'EIE', '11635', 'Athens', 'Vassileos Konstantinou ave.', '48', 'Research center');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('National Technical University of Athens', 'NTUA', '15780', 'Athens', 'Iroon Polytechniou', '9', 'University');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('National and Kapodistrian University of Athens', 'NKUA', '15784', 'Athens', 'Panepistimiopolis', null, 'University');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Aristotle University of Thessaloniki', 'AUTH', '54124', 'Thessaloniki', 'University Campus', null, 'University');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('University of Patras', 'Upatras', '26504', 'Patra', 'Panepistimioupolis', null, 'University');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('University of Crete', 'UOC', '74100', 'Rethymno', 'Panepistimioupolis of Rethymno', null, 'University');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('University of Ioannina', 'UOI', '45110', 'Ioannina', 'University Campus', null, 'University');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Aegean University', 'AEGEAN', '81100', 'Mitilini', 'Lofos Panepistimiou', null, 'University');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Democritus University Of Thrace', 'DUTH', '69100', 'Komotini', 'Panepistimioupolis', null, 'University');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('University of Peloponnese', 'UOP', '22100', 'Tripoli', 'Karaiskaki', '70', 'University');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Ionian University', 'IONU', '49100', 'Kerkira', 'Ioannou Theotoki', '72', 'University');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Motor oil', 'MO', '15124', 'Athens', 'Irodou Attikou', '12', 'Company');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Apivita', 'APVT', '19003', 'Markopoulo', 'Undustrial park', null, 'Company');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Elpedison', 'ELP', '14562', 'Athens', 'Kifissias ave', '282', 'Company');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Shell', 'SHELL', '16561', 'Athens', 'Andrea Papandreou', '141', 'Company');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Samsung', 'Samsung', '15125', 'Athens', 'Kifissias ave.', '84', 'Company');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Titan', 'TitSA', '11143', 'Athens', 'Chalkidos', '22', 'Company');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Vianex', 'VNX', '14671', 'Athens', 'Athinon-Lamias', '18', 'Company');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Cosmote', 'OTE', '16777', 'Athens', 'Iasonidou', '57', 'Company');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('Toyota', 'TYT', '16675', 'Athens', 'Miaouli', '24', 'Company');
insert into Organization (name, abbreviation, postal_code, city, street, street_number, organization_type) values ('BirdLife Greece', 'HOS', '14578', 'Athens', 'Thiseos', '95', 'Company');


insert into Program (department, program_name) values ('Department 1', 'Connecting Greece Facility');
insert into Program (department, program_name) values ('Department 1', 'Digital Greece');
insert into Program (department, program_name) values ('Department 2', 'National Space Program');
insert into Program (department, program_name) values ('Department 2', 'Programme for Environment and Climate Action');
insert into Program (department, program_name) values ('Department 2', 'Agricultural development of islands');
insert into Program (department, program_name) values ('Department 1', 'Creative Greece');
insert into Program (department, program_name) values ('Department 2', 'Green investments');
insert into Program (department, program_name) values ('Department 2', 'Productivity and sustainability of agriculture');
insert into Program (department, program_name) values ('Department 2', 'Agricultural and regional development');
insert into Program (department, program_name) values ('Department 4', 'Support for youth research and innovation');
insert into Program (department, program_name) values ('Department 3', 'Promotion of cultural culture');
insert into Program (department, program_name) values ('Department 4', 'Recovery and Resilience Facility');
insert into Program (department, program_name) values ('Department 5', 'Health for all');
insert into Program (department, program_name) values ('Department 3', 'Solidarity body');
insert into Program (department, program_name) values ('Department 3', 'Justice Program');
insert into Program (department, program_name) values ('Department 1', 'Greek arts');
insert into Program (department, program_name) values ('Department 3', 'Citizens, Equality, Rights and Values');
insert into Program (department, program_name) values ('Department 2', 'Maritime, Fisheries and Aquaculture Program');
insert into Program (department, program_name) values ('Department 3', 'Education for all');
insert into Program (department, program_name) values ('Department 3', 'Protection of cultural property');
insert into Program (department, program_name) values ('Department 4', 'Modern entrepreneurship');
insert into Program (department, program_name) values ('Department 5', 'Science in health');
insert into Program (department, program_name) values ('Department 2', 'Green transportation');
insert into Program (department, program_name) values ('Department 1', 'Digital pace');
insert into Program (department, program_name) values ('Department 1', 'Data science and evolution');
insert into Program (department, program_name) values ('Department 3', 'Learning from past');
insert into Program (department, program_name) values ('Department 2', 'Sustainable development');
insert into Program (department, program_name) values ('Department 2', 'Strengthening and establishing energy communities');
insert into Program (department, program_name) values ('Department 5', 'Robotics in surgery');
insert into Program (department, program_name) values ('Department 2', 'Urban rejuvenation');



insert into Phone (organization_id, phone) values ('1', '2103490000');
insert into Phone (organization_id, phone) values ('2', '2107474274');
insert into Phone (organization_id, phone) values ('3', '2291076462');
insert into Phone (organization_id, phone) values ('3', '2291076463');
insert into Phone (organization_id, phone) values ('4', '2810391500');
insert into Phone (organization_id, phone) values ('5', '2103664700');
insert into Phone (organization_id, phone) values ('6', '2106503000');
insert into Phone (organization_id, phone) values ('7', '2111069599');
insert into Phone (organization_id, phone) values ('7', '2111069598');
insert into Phone (organization_id, phone) values ('8', '2109656310');
insert into Phone (organization_id, phone) values ('9', '2103676300');
insert into Phone (organization_id, phone) values ('10', '2103480000');
insert into Phone (organization_id, phone) values ('10', '2103490001');
insert into Phone (organization_id, phone) values ('11', '2107721000');
insert into Phone (organization_id, phone) values ('12', '2107277000');
insert into Phone (organization_id, phone) values ('13', '2310996000');
insert into Phone (organization_id, phone) values ('14', '2610996683');
insert into Phone (organization_id, phone) values ('14', '2610996684');
insert into Phone (organization_id, phone) values ('15', '2810393229');
insert into Phone (organization_id, phone) values ('16', '2651007777');
insert into Phone (organization_id, phone) values ('17', '2251036000');
insert into Phone (organization_id, phone) values ('18', '2531039000');
insert into Phone (organization_id, phone) values ('19', '2710230000');
insert into Phone (organization_id, phone) values ('20', '2661087609');
insert into Phone (organization_id, phone) values ('20', '2661087608');
insert into Phone (organization_id, phone) values ('20', '2661087607');
insert into Phone (organization_id, phone) values ('21', '2104094161');
insert into Phone (organization_id, phone) values ('21', '2104094162');
insert into Phone (organization_id, phone) values ('22', '2102856350');
insert into Phone (organization_id, phone) values ('23', '2169006999');
insert into Phone (organization_id, phone) values ('24', '2109641339');
insert into Phone (organization_id, phone) values ('25', '2106897691');
insert into Phone (organization_id, phone) values ('26', '2106705200');
insert into Phone (organization_id, phone) values ('27', '2108003001');
insert into Phone (organization_id, phone) values ('28', '2109628000');
insert into Phone (organization_id, phone) values ('29', '2103445785');
insert into Phone (organization_id, phone) values ('30', '2109947551');


update University set government_funding = 10064068 where organization_id = 11;
update University set government_funding = 13226617 where organization_id = 12;
update University set government_funding = 5724875 where organization_id = 13;
update University set government_funding = 14005835 where organization_id = 14;
update University set government_funding = 10866836 where organization_id = 15;
update University set government_funding = 10693918 where organization_id = 16;
update University set government_funding = 5440239 where organization_id = 17;
update University set government_funding = 6335997 where organization_id = 18;
update University set government_funding = 5958414 where organization_id = 19;
update University set government_funding = 9757099 where organization_id = 20;


update Company set equity = 1638396772 where organization_id = 21;
update Company set equity = 3422525109 where organization_id = 22;
update Company set equity = 2141502289 where organization_id = 23;
update Company set equity = 3032068720 where organization_id = 24;
update Company set equity = 2137281883 where organization_id = 25;
update Company set equity = 3301297416 where organization_id = 26;
update Company set equity = 2257110948 where organization_id = 27;
update Company set equity = 1179525899 where organization_id = 28;
update Company set equity = 1639188130 where organization_id = 29;
update Company set equity = 476953662 where organization_id = 30;


update Research_center set government_funding = 7405765, private_equity = 3948310295 where organization_id = 1;
update Research_center set government_funding = 6280408, private_equity = 3782354722 where organization_id = 2;
update Research_center set government_funding = 2344651, private_equity = 2896419159 where organization_id = 3;
update Research_center set government_funding = 3826690, private_equity = 2145095862 where organization_id = 4;
update Research_center set government_funding = 4388808, private_equity = 868923357 where organization_id = 5;
update Research_center set government_funding = 7661665, private_equity = 2277927799 where organization_id = 6;
update Research_center set government_funding = 5397506, private_equity = 3407193649 where organization_id = 7;
update Research_center set government_funding = 6129130, private_equity = 2793482648 where organization_id = 8;
update Research_center set government_funding = 6439897, private_equity = 2702707284 where organization_id = 9;
update Research_center set government_funding = 2171541, private_equity = 633656085 where organization_id = 10;


insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Sydelle', 'Kirk', '1978-02-12', 1, '2013-07-10');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Cory', 'Maasze', '1964-06-22', 1, '2001-02-06');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Mikaela', 'Ackery', '1966-05-21', 1, '2002-02-10');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Wenda', 'Binnall', '1966-11-24', 1, '2012-01-11');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Marianne', 'Sandcroft', '1995-07-23', 2, '2021-02-01');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Jeri', 'Diloway', '1974-11-16', 2, '2017-12-15');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Kaycee', 'Chrystie', '1976-02-17', 2, '2019-07-01');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Ambur', 'Le Prevost', '1977-06-19', 3, '2004-10-18');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Corinne', 'McCarlich', '1974-05-09', 3, '2003-03-25');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Paloma', 'Brenton', '1971-10-12', 4, '1998-05-11');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Bidget', 'Maxstead', '1977-11-16', 4, '2009-02-24');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Harriette', 'Nern', '1961-08-30', 4, '2007-02-24');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Matelda', 'Marfe', '1984-07-30', 4, '2014-10-10');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Ronalda', 'Praten', '1961-10-16', 4, '2002-04-28');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Fan', 'Yuryaev', '1967-09-21', 4, '2001-08-26');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Katey', 'Kelway', '1969-03-29', 4, '1999-09-18');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Daniella', 'Lockyer', '1963-10-03', 5, '2005-10-02');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Cornie', 'Lerer', '1978-04-05', 6, '2006-01-30');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Giulietta', 'Wickins', '1977-02-02', 6, '2011-08-22');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Joellen', 'Zellick', '1983-06-09', 6, '2015-04-09');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Audy', 'Duncklee', '1970-11-29', 7, '2012-12-08');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Tessa', 'Sotham', '1982-09-27', 7, '2015-05-19');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Mariana', 'Myall', '1989-09-01', 7, '2011-01-07');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Helenka', 'de Copeman', '1975-06-09', 8, '2005-04-11');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Pearl', 'Kornousek', '1978-07-27', 8, '2021-01-19');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Jen', 'Colbridge', '1976-09-20', 9, '2007-09-18');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Ulla', 'Measor', '1960-01-14', 10, '2009-05-11');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Cristi', 'Collidge', '1977-10-20', 10, '2009-03-24');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Astra', 'Morecombe', '1982-02-01', 10, '2016-08-12');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Evangeline', 'Kynastone', '1978-07-15', 11, '2006-08-20');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Amelie', 'Durand', '1982-08-26', 11, '2010-06-15');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Lexi', 'Baker', '1967-06-21', 12, '2021-11-18');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Annabel', 'Bushby', '1963-07-25', 12, '2011-06-03');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Eveleen', 'Attfield', '1975-01-12', 12, '2017-06-05');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Grethel', 'Clay', '1988-12-09', 12, '2012-10-04');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Bobbie', 'Vagg', '1992-08-15', 13, '2017-11-21');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Mireielle', 'Thewles', '1981-02-01', 13, '2015-04-09');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Marrilee', 'O''Daly', '1978-08-25', 13, '2013-01-01');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Tanhya', 'Barkshire', '1971-05-20', 14, '2014-06-16');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Emmi', 'Snow', '1980-06-20', 14, '2019-04-10');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Lindsey', 'Stother', '1989-04-29', 15, '2020-02-05');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Giovanna', 'Paolucci', '1975-05-10', 15, '2004-12-26');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Karole', 'Auguste', '1962-09-26', 15, '2011-12-31');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Adela', 'Welfare', '1963-09-26', 15, '2005-04-18');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Tracie', 'Bucknall', '1978-01-01', 15, '2007-01-10');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Tommy', 'Ferrand', '1977-11-10', 15, '2016-09-17');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Fredrika', 'Stovold', '1970-01-02', 15, '2007-02-28');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Mona', 'Brunini', '1960-07-11', 15, '2014-03-28');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Pauline', 'Kendle', '1986-01-26', 16, '2010-08-09');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Janeczka', 'Mullany', '1984-11-15', 16, '2019-04-10');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Shadow', 'Entissle', '1964-11-16', 16, '2002-08-20');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Efren', 'Dallywater', '1985-08-23', 17, '2010-07-15');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Kalvin', 'Legier', '1974-07-27', 17, '2021-01-14');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Alvin', 'Beeching', '1969-03-08', 17, '2001-08-16');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Jerad', 'Gillum', '1963-12-06', 17, '2013-07-06');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Ogdon', 'Yurasov', '1991-04-19', 18, '2021-12-08');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Gerardo', 'Levett', '1960-09-05', 19, '2011-02-12');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Albrecht', 'Hancke', '1971-06-08', 19, '2001-10-12');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Cordell', 'Berthon', '1970-09-08', 20, '2009-04-19');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Beniamino', 'Oldmeadow', '1967-04-02', 20, '2007-03-04');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Jocko', 'Raimbauld', '1960-09-09', 21, '2006-05-10');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Lyle', 'Peter', '1961-06-27', 21, '2019-01-10');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Paddy', 'O''Dea', '1994-09-05', 21, '2020-05-15');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Tanny', 'Dunnet', '1974-08-21', 21, '2017-08-19');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Denny', 'Pock', '1980-12-21', 21, '2021-08-19');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Carlyle', 'Mussett', '1983-11-07', 22, '2015-04-15');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Wolf', 'McIlraith', '1969-04-05', 22, '2010-03-10');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Denny', 'Morillas', '1988-08-18', 22, '2014-07-03');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Jereme', 'Lancetter', '1987-06-27', 22, '1999-04-28');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Bartholomew', 'McGavigan', '1965-10-14', 22, '2008-05-05');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Isidoro', 'McQuillin', '1966-04-19', 22, '2020-02-25');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Marcello', 'McQuorkel', '1986-04-23', 23, '2019-06-23');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Mitchel', 'McMillian', '1963-12-15', 23, '2005-11-26');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Broddy', 'Poure', '1988-10-19', 23, '2008-03-17');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Bo', 'Curry', '1966-01-03', 24, '2014-10-30');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Lionel', 'Keats', '1964-11-02', 24, '2004-06-19');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Holden', 'Swiffin', '1971-07-01', 24, '2000-11-27');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Tonnie', 'Paulley', '1972-03-26', 25, '2010-12-05');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Armando', 'Pigdon', '1960-08-09', 25, '1998-04-18');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Theobald', 'Eagleton', '1995-08-21', 25, '2021-09-01');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Felix', 'Rickett', '1991-07-05', 25, '2018-05-11');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Miguel', 'Markwick', '1974-12-17', 25, '2013-05-28');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Fonz', 'Rosier', '1987-06-24', 25, '2021-02-21');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Bjorn', 'Bartels-Ellis', '1986-09-29', 26, '2022-03-13');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Judah', 'Glasscoo', '1990-06-17', 26, '2016-12-18');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Penrod', 'Gouda', '1965-07-20', 26, '2015-10-18');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Park', 'Klimashevich', '1964-06-30', 27, '2002-01-05');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Tore', 'Cammish', '1968-04-07', 27, '2021-10-11');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Delainey', 'Richichi', '1972-04-03', 27, '2013-01-05');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Mahmud', 'Kollaschek', '1990-01-17', 27, '2018-12-23');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Mitchel', 'MacSween', '1978-04-27', 28, '2016-06-16');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Marwin', 'Soro', '1969-01-14', 28, '2005-12-31');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Lorin', 'Dolphin', '1973-11-09', 28, '2007-02-21');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Myles', 'Croster', '1981-10-30', 28, '2020-03-07');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Spence', 'Brinsden', '1990-04-13', 29, '2016-07-22');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Hilton', 'Fortnam', '1966-08-08', 29, '2007-04-25');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Haskel', 'Fauguel', '1966-08-26', 29, '2007-09-04');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Hurley', 'Boards', '1973-12-30', 30, '2018-05-22');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Hubey', 'Hebbes', '1993-02-15', 30, '2020-08-09');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Wade', 'Antoniak', '1962-10-24', 30, '1999-02-21');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Wall', 'Mike', '1990-10-24', 22, '2019-02-21');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Anna', 'Boards', '1975-12-30', 30, '2018-05-22');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Lagertha', 'Hebbes', '1987-02-15', 30, '2018-08-09');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Torvi', 'Antoniak', '1962-01-24', 30, '2017-02-21');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'John', 'Snow', '1975-12-30', 29, '2018-05-22');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('male', 'Tyrion', 'Lannister', '1987-02-15', 29, '2018-08-09');
insert into Researcher (sex, first_name, last_name, date_of_birth, organization_id, work_starting_day) values ('female', 'Emilia', 'Clark', '1992-01-24', 29, '2017-02-21');



insert into Executive (first_name, last_name) values ('Kirbee', 'Threlkeld');
insert into Executive (first_name, last_name) values ('Charmaine', 'Brenstuhl');
insert into Executive (first_name, last_name) values ('Clevey', 'Panks');
insert into Executive (first_name, last_name) values ('Lynne', 'Giddins');
insert into Executive (first_name, last_name) values ('Torrie', 'Pethybridge');
insert into Executive (first_name, last_name) values ('Barret', 'Evamy');
insert into Executive (first_name, last_name) values ('Jo', 'Aleksankov');
insert into Executive (first_name, last_name) values ('Ailey', 'Ricketts');
insert into Executive (first_name, last_name) values ('Alis', 'Dummigan');
insert into Executive (first_name, last_name) values ('Fianna', 'Shenfish');
insert into Executive (first_name, last_name) values ('Valery', 'Varrow');
insert into Executive (first_name, last_name) values ('Ambrosi', 'Asty');
insert into Executive (first_name, last_name) values ('Corny', 'Pomfret');
insert into Executive (first_name, last_name) values ('Thorny', 'Keemer');
insert into Executive (first_name, last_name) values ('Steward', 'Sunter');
insert into Executive (first_name, last_name) values ('Ragnar', 'Lothbrok');
insert into Executive (first_name, last_name) values ('Daniel', 'Colt');


insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Quantum calculations with supercold atom clouds', 'Description', 114379, '2014-09-19', '2016-09-14', 1, 92, 3, 1, 1, 3.8, '2013-09-09');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Flammable Greece – Increasing awareness and preparedness for extreme fire weather and behavior', 'Description', 293246, '2021-11-28', '2023-08-17', 2, 16, 3, 2, 1, 3.1, '2019-06-19');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Upgraded Materials for solar cells', 'Description', 228912, '2021-04-30', '2025-03-02', 3, 36, 5, 3, 2, 9.5, '2020-12-06');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Reduction of groundwater reserves', 'Description', 145594, '2021-05-06', '2024-03-03', 4, 45, 5, 4, 2, 7.1, '2019-09-28');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('The mechanisms of fluid-inducted seismicity', 'Description', 255891, '2022-01-30', '2025-02-14', 5, 87, 8, 5, 3, 4.5, '2021-12-28');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Complex macrocyclic compounds', 'Description', 114281, '2020-12-23', '2023-12-03', 6, 33, 10, 6, 4, 3.8, '2019-04-13');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Innovative photonic meta surfaces with multiple tunings for broadband light control', 'Description', 13125, '2020-01-16', '2023-03-09', 7, 1, 10, 7, 4, 2.4, '2019-11-26');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Timeless approach to rutal architecure', 'Description', 222351, '2020-08-25', '2022-11-10', 8, 26, 11, 8, 4, 3.4, '2017-07-23');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Enzymatic coexistence in biomass utilization', 'Description', 163292, '2020-02-08', '2023-05-26', 2, 81, 17, 2, 5, 8.5, '2019-07-14');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Dynamics methods for complex building systems', 'Description', 286520, '2020-08-14', '2023-12-06', 9, 6, 18, 9, 6, 4.8, '2019-03-25');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Advanced structural information model for safer constructions against man-made hazards', 'Description', 270844, '2015-09-21', '2018-06-07', 10, 60, 20, 10, 6, 2.7, '2011-11-28');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Development of an optimized unmanned aerial vehicle platform', 'Description', 215628, '2021-09-24', '2024-09-20', 11, 87, 21, 11, 7, 8.0, '2020-05-09');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Improving the resilience of transport infrastructure to natural hazards', 'Description', 177348, '2020-06-30', '2023-09-21', 12, 2, 21, 12, 7, 9.2, '2018-03-31');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Innovative Textile Structures for Mechanical Electromagnetic Reconfigurability of Wearable Antennas', 'Description', 210724, '2021-05-22', '2024-10-18', 13, 3, 24, 13, 8, 6.7, '2019-01-31');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Investigation of T regulatory cells in autoimmunity for therapeutic targeting', 'Description', 273047, '2021-05-19', '2024-06-22', 14, 84, 26, 14, 9, 3.8, '2018-09-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Study of the effect of genetic alterations on cellular metabolism', 'Description', 180832, '2014-04-14', '2016-11-23', 15, 39, 27, 15, 10, 6.7, '2011-02-14');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Light chain and amyloid-induced cardiotoxicity study', 'Description', 174824, '2011-11-07', '2012-11-10', 16, 20, 29, 1, 10, 9.2, '2010-12-13');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Scalable molecular dynamics with NAMD', 'Description', 204680, '2019-05-01', '2022-12-26', 17, 6, 30, 2, 11, 7.1, '2018-01-13');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Pathogenesis of type 2 diabetes mellitus', 'Description', 198364, '2022-01-06', '2024-02-15', 18, 24, 34, 3, 12, 8.0, '2021-11-22');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Role of mechanical forces on aging and cancer', 'Description', 128519, '2011-12-03', '2015-06-03', 19, 10, 34, 4, 12, 5.4, '2011-02-24');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('INteractions of Veterinary antibiotics with soil microorganisms: exploiting microbial degradation to avert Environmental contamination and ResisTance dispersal', 'Description', 155868, '2018-02-02', '2021-10-25', 20, 15, 36, 5, 13, 1.2, '2017-02-12');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Degrading enzymes of osmogenic molecules', 'Description', 172610, '2024-04-29', '2027-07-07', 21, 90, 39, 6, 14, 8.1, '2022-04-10');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Molecular Cooking:Amino Acids Trap Silicon in Carbon Matrix to Boost Lithium-Ion Storage', 'Description', 100344, '2021-10-13', '2023-06-16', 22, 15, 41, 7, 15, 9.5, '2020-06-30');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Arthroscopic approach to acute bony Bankart lesion', 'Description', 116968, '2021-04-25', '2023-03-10', 23, 99, 48, 8, 15, 2.0, '2020-01-27');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Responsible by Design Entity Resolution', 'Description', 239235, '2021-11-10', '2024-11-20', 24, 15, 48, 9, 15, 8.2, '2020-01-14');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('iQARuS – Αποδοτική αποτίμηση ερωτήσεων πάνω από διασυνδεδεμένα δεδομένα ροής με χρήση συνόψεων', 'Description', 242513, '2021-04-14', '2024-08-05', 25, 8, 51, 10, 16, 5.9, '2019-11-24');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Lifting Algorithms for Evolutionary Dynamics in Networks (LIFT)', 'Description', 121869, '2021-09-23', '2025-06-08', 26, 81, 51, 11, 16, 3.3, '2018-05-26');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('On the Great Greek Brain Drain: A Macroeconomic Approach (GREBRAD)', 'Description', 276618, '2021-12-07', '2024-10-16', 27, 20, 52, 12, 17, 4.0, '2021-02-09');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Evaluating a training intervention in Greek Midwifery school graduates for the retention of skills in shoulder dystocia management with the use of high-fidelity simulation: the SAFE (SimulAtion high-FidElity) study', 'Description', 179540, '2020-08-07', '2023-06-19', 28, 75, 55, 13, 17, 8.4, '2019-09-05');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Chemistry and technology of silicone', 'Description', 236535, '2019-09-20', '2023-05-17', 29, 38, 56, 14, 18, 8.8, '2018-04-06');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('GREEK FRAGMENTARY TRAGEDIANS ONLINE  Part I: 6th- 5th Century BC', 'Description', 272070, '2020-10-18', '2023-12-02', 25, 52, 58, 10, 19, 2.6, '2019-10-11');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Contextualizing biobanking in Greece: histories, practices, discourses', 'Description', 176314, '2021-08-20', '2023-09-06', 30, 29, 59, 15, 20, 8.0, '2019-03-30');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Nanotechnological applications in medicine', 'Description', 108230, '2019-10-12', '2022-08-05', 18, 10, 61, 3, 21, 8.5, '2018-11-08');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Integrated optimization of smart home appliances with cost-effective energy management system', 'Description', 212013, '2021-05-18', '2024-08-02', 30, 99, 65, 15, 21, 6.4, '2019-04-05');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Smart ELectric Vehicles Integration in electric energy Systems (ELVIS)', 'Description', 157903, '2019-05-26', '2022-07-18', 15, 97, 66, 15, 22, 4.3, '2018-04-03');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Assessment of naTuraL and ANThropogenic AerosolS impact on climate (ATLANTAS)', 'Description', 138555, '2020-03-29', '2023-07-04', 10, 16, 66, 10, 22, 2.8, '2018-10-06');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Mineralogy of Dust Emissions and impacts on Environment and Health', 'Description', 227897, '2022-04-09', '2025-12-09', 25, 90, 70, 10, 22, 7.9, '2020-01-20');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Modeling distributed lag effects in epidemiological time series studies', 'Description', 105529, '2019-09-04', '2023-03-18', 27, 30, 72, 12, 23, 10.0, '2018-07-17');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Economic implications for the generation of electricity from biomass fuel sources', 'Description', 202510, '2019-09-03', '2022-12-17', 3, 17, 72, 3, 23, 9.9, '2017-07-31');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('An enhanced security framework for home appliances in smart home', 'Description', 144177, '2011-10-31', '2014-08-11', 9, 17, 75, 9, 24, 8.6, '2010-01-02');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Smart technologies in everyday life', 'Description', 279293, '2018-12-04', '2022-10-07', 7, 100, 79, 7, 25, 8.2, '2017-10-13');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Green technologies in modern cities ', 'Description', 113441, '2020-07-01', '2023-08-18', 12, 16, 80, 12, 25, 1.5, '2018-06-15');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Sampling nodes in large networks', 'Description', 157732, '2021-09-16', '2025-08-22', 13, 8, 81, 13, 25, 3.2, '2020-07-13');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('New approach to pattern recognition', 'Description', 203197, '2022-01-14', '2025-09-19', 13, 36, 85, 13, 26, 9.0, '2021-03-19');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Importance of sign language in education', 'Description', 191860, '2020-09-12', '2023-04-01', 17, 27, 87, 2, 27, 2.5, '2019-05-26');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Personalized applications to change the user;s energy behavior ', 'Description', 243299, '2021-07-27', '2024-05-16', 11, 15, 90, 11, 27, 8.1, '2018-01-04');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Oil mining with EOR-PNP', 'Description', 191927, '2020-04-25', '2023-06-14', 30, 79, 92, 15, 28, 2.8, '2019-06-03');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Effective algorithms for network analysis', 'Description', 133884, '2022-04-23', '2025-09-23', 13, 2, 96, 13, 29, 8.0, '2020-02-24');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Data Science for All', 'Description', 240613, '2022-03-26', '2025-03-12', 30, 62, 100, 15, 30, 9.8, '2021-01-11');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Efficient Lineage for SUM Aggregate Queries', 'Description', 160571, '2021-10-02', '2025-09-27', 26, 58, 100, 11, 30, 8.6, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Dyneins:molecular structure and cellular function', 'Description', 170571, '2021-10-02', '2025-09-27', 13, 2, 96, 13, 29, 8.0, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('The molecular structure of green fluorescent protein', 'Description', 180571, '2021-10-02', '2025-09-27', 13, 2, 96, 13, 29, 8.0, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Nanotechnology : Advantages and drawbacks in the field of construction and building material ', 'Description', 190571, '2021-10-02', '2025-09-27', 13, 2, 96, 13, 29, 8.0, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Embodied energy of common and alternative building materials and technologies', 'Description', 160671, '2021-10-02', '2025-09-27', 13, 2, 96, 13, 29, 8.0, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Photocatalytic construction and building materials: from fundamentals to applications', 'Description', 160471, '2021-10-02', '2025-09-27', 13, 2, 96, 13, 29, 8.0, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Nanotechnology applications in cancer', 'Description', 160581, '2021-10-02', '2025-09-27', 13, 2, 96, 13, 29, 8.0, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Applications of nanotechnology for immunology', 'Description', 160521, '2021-10-02', '2025-09-27', 13, 2, 96, 13, 29, 8.0, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Applications of micro-fourier transform infrared spectroscopy (FTIR) in the geological sciences—a review', 'Description', 160171, '2021-10-02', '2025-09-27', 13, 2, 96, 13, 29, 8.0, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Investigation on the antimicrobial properties of cerium‐doped bioactive glasses', 'Description', 163571, '2021-10-02', '2025-09-27', 13, 2, 96, 13, 29, 8.0, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Analysis on the development law of active geological hazards in the Loess Plateau based on InSAR identification', 'Description', 159771, '2021-10-02', '2025-09-27', 13, 2, 96, 13, 29, 8.0, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Method for accurately measuring reopening pressure of hydraulic fracturing induced fracture in deep borehole', 'Description', 121471, '2021-10-02', '2025-09-27', 26, 58, 100, 11, 30, 8.6, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Formation of a system of intelligent analysis of geological data based on ontological engineering', 'Description', 169771, '2021-10-02', '2025-09-27', 26, 58, 100, 11, 30, 8.6, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Blockchain Technology for Intelligent Transportation Systems: A Systematic Literature Review', 'Description', 124571, '2021-10-02', '2025-09-27', 26, 58, 100, 11, 30, 8.6, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Time-Constrained Ensemble Sensing With Heterogeneous IoT Devices in Intelligent Transportation Systems', 'Description', 200571, '2021-10-02', '2025-09-27', 26, 58, 100, 11, 30, 8.6, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Analysis of Vehicle Location Prediction Errors for Safety Applications in Cooperative-Intelligent Transportation Systems', 'Description', 110571, '2021-10-02', '2025-09-27', 26, 58, 100, 11, 30, 8.6, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Blockchain-Based Software-Defined Vehicular Networks for Intelligent Transportation System Beyond 5G', 'Description', 350571, '2021-10-02', '2025-09-27', 26, 58, 100, 11, 30, 8.6, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Big Data for Healthcare Industry 4.0: Applications, challenges and future perspectives', 'Description', 150571, '2021-10-02', '2025-09-27', 26, 58, 100, 11, 30, 8.6, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Blockchain technology in healthcare: Challenges and opportunities', 'Description', 460571, '2021-10-02', '2025-09-27', 26, 58, 100, 11, 30, 8.6, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Environmental impact of information and communication technology: Unveiling the role of education in developing countries', 'Description', 169577, '2021-10-02', '2025-09-27', 26, 58, 100, 11, 30, 8.6, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('The environmental impact of mass coronavirus vaccinations: A point of view on huge COVID-19 vaccine waste across the globe during ongoing vaccine campaigns', 'Description', 168572, '2021-10-02', '2025-09-27', 26, 58, 100, 11, 30, 8.6, '2020-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Using hydrocolloids to decrease oil absorption in banana chips', 'Description', 108572, '2020-11-03', '2022-09-27', 26, 3, 99, 16, 30, 8.6, '2018-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Physico-chemical changes during different stages of MFD/FD banana chips', 'Description', 138572, '2020-01-04', '2023-04-20', 26, 4, 99, 16, 30, 8.6, '2019-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('The response of photosynthesis and stomatal conductance to rising [CO2]: mechanisms and environmental interactions', 'Description', 102572, '2020-02-05', '2021-04-05', 26, 5, 99, 16, 30, 8.6, '2019-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('The chemical effect of CO2 replacement of N2 in air on the burning velocity of CH4 and H2 premixed flames', 'Description', 102554, '2020-03-06', '2022-03-18', 26, 6, 99, 16, 30, 8.6, '2017-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Estimating EU fossil fuel CO2 emissions from measurements of 14C in atmospheric CO2', 'Description', 114172, '2020-04-07', '2023-02-15', 26, 7, 99, 16, 30, 8.6, '2020-01-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Biotechnology and microbiology of coal degradation', 'Description', 120072, '2020-05-08', '2022-05-17', 26, 8, 99, 16, 30, 8.6, '2020-02-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('The importance of nutrient management for potato production Part I: Plant nutrition and yield', 'Description', 142572, '2020-06-09', '2023-03-27', 26, 9, 99, 16, 30, 8.6, '2020-01-05');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Agriculture 4.0: The future of farming technology', 'Description', 161245, '2020-07-12', '2022-10-27', 26, 10, 99, 16, 30, 8.6, '2020-01-12');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Real-world carbon dioxide impacts of traffic congestion', 'Description', 198745, '2020-08-22', '2023-05-17', 26, 11, 99, 16, 30, 8.6, '2019-04-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Cancer chemopreventive potential of apples, apple juice, and apple components', 'Description', 298745, '2020-09-24', '2022-09-10', 26, 12, 99, 16, 30, 8.6, '2018-06-01');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Thermosonication as a potential quality enhancement technique of apple juice', 'Description', 198726, '2020-11-30', '2023-09-01', 26, 13, 99, 16, 30, 8.6, '2020-02-01');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Characterization of tequila flavor by instrumental and sensory analysis', 'Description', 208572, '2020-11-03', '2022-09-27', 26, 3, 105, 17, 29, 8.6, '2018-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('What makes a strong team? Using collective intelligence to predict team performance in League of Legends', 'Description', 158572, '2020-01-04', '2023-04-20', 26, 4, 105, 17, 29, 8.6, '2019-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Mechanics and Metagame: Exploring Binary Expertise in League of Legends', 'Description', 142572, '2020-02-05', '2021-04-05', 26, 5, 105, 17, 29, 8.6, '2019-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('A Review on blockchain applications in the agri-food sector', 'Description', 202554, '2020-03-06', '2022-03-18', 26, 6, 105, 17, 29, 8.6, '2017-06-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Analytical methodologies for determination of artificial sweeteners in foodstuffs', 'Description', 174172, '2020-04-07', '2023-02-15', 26, 7, 105, 17, 29, 8.6, '2020-01-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Artificial intelligence, robotics, advanced technologies and human resource management: a systematic review', 'Description', 190072, '2020-05-08', '2022-05-17', 26, 8, 105, 17, 29, 8.6, '2020-02-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Impact of artificial intelligence, robotics, and machine learning on sales and marketing', 'Description', 182572, '2020-06-09', '2023-03-27', 26, 9, 106, 17, 29, 8.6, '2020-01-05');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Magnetization of hard superconductors', 'Description', 261245, '2020-07-12', '2022-10-27', 26, 10, 106, 17, 29, 8.6, '2020-01-12');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('Carbon materials for supercapacitor application', 'Description', 208745, '2020-08-22', '2023-05-17', 26, 11, 106, 17, 29, 8.6, '2019-04-18');
insert into Project (project_title, description, funding_amount, starting_date, ending_date, program_id, evaluator_id, supervisor_id, executive_id, organization_id, evaluation_grade, evaluation_date) values ('A review of supercapacitor modeling, estimation, and applications: A control/management perspective', 'Description', 198745, '2020-09-24', '2022-09-10', 26, 12, 106, 17, 29, 8.6, '2018-06-01');


insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (1, 'Deliverable1.1', 'Description', '2015-02-23');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (1, 'Deliverable1.2', 'Description', '2015-11-20');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (2, 'Deliverable2', 'Description', '2022-03-11');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (3, 'Deliverable3', 'Description', '2023-12-22');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (4, 'Deliverable4', 'Description', '2022-01-24');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (5, 'Deliverable5', 'Description', '2023-07-04');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (6, 'Deliverable6', 'Description', '2021-01-24');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (7, 'Deliverable7.1', 'Description', '2021-10-27');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (7, 'Deliverable7.2', 'Description', '2022-06-10');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (8, 'Deliverable8', 'Description', '2021-06-10');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (9, 'Deliverable9', 'Description', '2022-01-24');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (10, 'Deliverable10', 'Description', '2022-01-24');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (11, 'Deliverable11', 'Description', '2017-03-31');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (12, 'Deliverable12', 'Description', '2022-06-19');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (13, 'Deliverable13', 'Description', '2021-06-15');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (14, 'Deliverable14.1', 'Description', '2022-01-24');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (14, 'Deliverable14.2', 'Description', '2023-03-22');
insert into Deliverable (project_id, deliverable_title, description, delivery_date) values (15, 'Deliverable15', 'Description', '2022-11-29');


insert into Scientific_field (field_name) values ('Physical Sciences');
insert into Scientific_field (field_name) values ('Engineering and Technology');
insert into Scientific_field (field_name) values ('Medicine and Health');
insert into Scientific_field (field_name) values ('Geological Sciences');
insert into Scientific_field (field_name) values ('Maths and Data science');
insert into Scientific_field (field_name) values ('Social Sciences');
insert into Scientific_field (field_name) values ('Humanities and Art');
insert into Scientific_field (field_name) values ('Environment and Energy');
insert into Scientific_field (field_name) values ('Accounting and Finance');


insert into Concerns (scientific_id, project_id) values (1, 1);
insert into Concerns (scientific_id, project_id) values (8, 1);
insert into Concerns (scientific_id, project_id) values (5, 1);
insert into Concerns (scientific_id, project_id) values (1, 2);
insert into Concerns (scientific_id, project_id) values (8, 2);
insert into Concerns (scientific_id, project_id) values (4, 2);
insert into Concerns (scientific_id, project_id) values (1, 3);
insert into Concerns (scientific_id, project_id) values (8, 4);
insert into Concerns (scientific_id, project_id) values (1, 4);
insert into Concerns (scientific_id, project_id) values (4, 4);
insert into Concerns (scientific_id, project_id) values (2, 4);
insert into Concerns (scientific_id, project_id) values (1, 5);
insert into Concerns (scientific_id, project_id) values (4, 5);
insert into Concerns (scientific_id, project_id) values (8, 5);
insert into Concerns (scientific_id, project_id) values (1, 6);
insert into Concerns (scientific_id, project_id) values (3, 6);
insert into Concerns (scientific_id, project_id) values (1, 7);
insert into Concerns (scientific_id, project_id) values (7, 8);
insert into Concerns (scientific_id, project_id) values (2, 8);
insert into Concerns (scientific_id, project_id) values (2, 9);
insert into Concerns (scientific_id, project_id) values (4, 9);
insert into Concerns (scientific_id, project_id) values (4, 10);
insert into Concerns (scientific_id, project_id) values (8, 10);
insert into Concerns (scientific_id, project_id) values (2, 10);
insert into Concerns (scientific_id, project_id) values (2, 11);
insert into Concerns (scientific_id, project_id) values (4, 11);
insert into Concerns (scientific_id, project_id) values (8, 11);
insert into Concerns (scientific_id, project_id) values (2, 12);
insert into Concerns (scientific_id, project_id) values (2, 13);
insert into Concerns (scientific_id, project_id) values (8, 13);
insert into Concerns (scientific_id, project_id) values (2, 14);
insert into Concerns (scientific_id, project_id) values (3, 15);
insert into Concerns (scientific_id, project_id) values (3, 16);
insert into Concerns (scientific_id, project_id) values (2, 16);
insert into Concerns (scientific_id, project_id) values (3, 17);
insert into Concerns (scientific_id, project_id) values (2, 17);
insert into Concerns (scientific_id, project_id) values (3, 18);
insert into Concerns (scientific_id, project_id) values (4, 18);
insert into Concerns (scientific_id, project_id) values (8, 18);
insert into Concerns (scientific_id, project_id) values (3, 19);
insert into Concerns (scientific_id, project_id) values (2, 19);
insert into Concerns (scientific_id, project_id) values (4, 19);
insert into Concerns (scientific_id, project_id) values (8, 19);
insert into Concerns (scientific_id, project_id) values (3, 20);
insert into Concerns (scientific_id, project_id) values (2, 20);
insert into Concerns (scientific_id, project_id) values (4, 20);
insert into Concerns (scientific_id, project_id) values (8, 20);
insert into Concerns (scientific_id, project_id) values (4, 21);
insert into Concerns (scientific_id, project_id) values (1, 21);
insert into Concerns (scientific_id, project_id) values (2, 21);
insert into Concerns (scientific_id, project_id) values (8, 21);
insert into Concerns (scientific_id, project_id) values (4, 22);
insert into Concerns (scientific_id, project_id) values (2, 22);
insert into Concerns (scientific_id, project_id) values (5, 22);
insert into Concerns (scientific_id, project_id) values (4, 23);
insert into Concerns (scientific_id, project_id) values (2, 23);
insert into Concerns (scientific_id, project_id) values (5, 23);
insert into Concerns (scientific_id, project_id) values (1, 24);
insert into Concerns (scientific_id, project_id) values (2, 24);
insert into Concerns (scientific_id, project_id) values (5, 24);
insert into Concerns (scientific_id, project_id) values (8, 24);
insert into Concerns (scientific_id, project_id) values (5, 25);
insert into Concerns (scientific_id, project_id) values (8, 25);
insert into Concerns (scientific_id, project_id) values (5, 26);
insert into Concerns (scientific_id, project_id) values (6, 26);
insert into Concerns (scientific_id, project_id) values (7, 26);
insert into Concerns (scientific_id, project_id) values (5, 27);
insert into Concerns (scientific_id, project_id) values (9, 27);
insert into Concerns (scientific_id, project_id) values (8, 27);
insert into Concerns (scientific_id, project_id) values (2, 27);
insert into Concerns (scientific_id, project_id) values (6, 28);
insert into Concerns (scientific_id, project_id) values (2, 28);
insert into Concerns (scientific_id, project_id) values (5, 28);
insert into Concerns (scientific_id, project_id) values (7, 28);
insert into Concerns (scientific_id, project_id) values (9, 28);
insert into Concerns (scientific_id, project_id) values (6, 29);
insert into Concerns (scientific_id, project_id) values (9, 29);
insert into Concerns (scientific_id, project_id) values (6, 30);
insert into Concerns (scientific_id, project_id) values (7, 30);
insert into Concerns (scientific_id, project_id) values (8, 30);
insert into Concerns (scientific_id, project_id) values (7, 31);
insert into Concerns (scientific_id, project_id) values (7, 32);
insert into Concerns (scientific_id, project_id) values (2, 32);
insert into Concerns (scientific_id, project_id) values (5, 32);
insert into Concerns (scientific_id, project_id) values (8, 32);
insert into Concerns (scientific_id, project_id) values (7, 33);
insert into Concerns (scientific_id, project_id) values (2, 33);
insert into Concerns (scientific_id, project_id) values (4, 33);
insert into Concerns (scientific_id, project_id) values (5, 33);
insert into Concerns (scientific_id, project_id) values (8, 34);
insert into Concerns (scientific_id, project_id) values (4, 34);
insert into Concerns (scientific_id, project_id) values (8, 35);
insert into Concerns (scientific_id, project_id) values (5, 35);
insert into Concerns (scientific_id, project_id) values (2, 35);
insert into Concerns (scientific_id, project_id) values (8, 36);
insert into Concerns (scientific_id, project_id) values (5, 36);
insert into Concerns (scientific_id, project_id) values (8, 37);
insert into Concerns (scientific_id, project_id) values (8, 38);
insert into Concerns (scientific_id, project_id) values (2, 38);
insert into Concerns (scientific_id, project_id) values (4, 38);
insert into Concerns (scientific_id, project_id) values (8, 39);
insert into Concerns (scientific_id, project_id) values (9, 40);
insert into Concerns (scientific_id, project_id) values (5, 40);
insert into Concerns (scientific_id, project_id) values (2, 40);
insert into Concerns (scientific_id, project_id) values (9, 41);
insert into Concerns (scientific_id, project_id) values (9, 42);
insert into Concerns (scientific_id, project_id) values (2, 42);
insert into Concerns (scientific_id, project_id) values (2, 43);
insert into Concerns (scientific_id, project_id) values (5, 43);
insert into Concerns (scientific_id, project_id) values (2, 44);
insert into Concerns (scientific_id, project_id) values (2, 45);
insert into Concerns (scientific_id, project_id) values (5, 45);
insert into Concerns (scientific_id, project_id) values (8, 45);
insert into Concerns (scientific_id, project_id) values (2, 46);
insert into Concerns (scientific_id, project_id) values (2, 47);
insert into Concerns (scientific_id, project_id) values (5, 47);
insert into Concerns (scientific_id, project_id) values (5, 48);
insert into Concerns (scientific_id, project_id) values (2, 48);
insert into Concerns (scientific_id, project_id) values (9, 48);
insert into Concerns (scientific_id, project_id) values (5, 49);
insert into Concerns (scientific_id, project_id) values (5, 50);
insert into Concerns (scientific_id, project_id) values (9, 50);
insert into Concerns (scientific_id, project_id) values (5, 51);
insert into Concerns (scientific_id, project_id) values (2, 52);
insert into Concerns (scientific_id, project_id) values (8, 53);
insert into Concerns (scientific_id, project_id) values (5, 54);
insert into Concerns (scientific_id, project_id) values (8, 55);
insert into Concerns (scientific_id, project_id) values (8, 56);
insert into Concerns (scientific_id, project_id) values (2, 57);
insert into Concerns (scientific_id, project_id) values (4, 58);
insert into Concerns (scientific_id, project_id) values (8, 59);
insert into Concerns (scientific_id, project_id) values (9, 60);
insert into Concerns (scientific_id, project_id) values (5, 61);
insert into Concerns (scientific_id, project_id) values (2, 62);
insert into Concerns (scientific_id, project_id) values (9, 63);
insert into Concerns (scientific_id, project_id) values (9, 64);
insert into Concerns (scientific_id, project_id) values (2, 65);
insert into Concerns (scientific_id, project_id) values (2, 66);
insert into Concerns (scientific_id, project_id) values (5, 67);
insert into Concerns (scientific_id, project_id) values (2, 68);
insert into Concerns (scientific_id, project_id) values (2, 69);
insert into Concerns (scientific_id, project_id) values (5, 70);
insert into Concerns (scientific_id, project_id) values (8, 51);
insert into Concerns (scientific_id, project_id) values (7, 52);
insert into Concerns (scientific_id, project_id) values (2, 53);
insert into Concerns (scientific_id, project_id) values (6, 54);
insert into Concerns (scientific_id, project_id) values (5, 55);
insert into Concerns (scientific_id, project_id) values (2, 56);
insert into Concerns (scientific_id, project_id) values (9, 57);
insert into Concerns (scientific_id, project_id) values (5, 58);
insert into Concerns (scientific_id, project_id) values (5, 59);
insert into Concerns (scientific_id, project_id) values (4, 60);
insert into Concerns (scientific_id, project_id) values (2, 91);
insert into Concerns (scientific_id, project_id) values (2, 82);
insert into Concerns (scientific_id, project_id) values (5, 83);
insert into Concerns (scientific_id, project_id) values (2, 84);
insert into Concerns (scientific_id, project_id) values (1, 85);
insert into Concerns (scientific_id, project_id) values (5, 86);
insert into Concerns (scientific_id, project_id) values (8, 87);
insert into Concerns (scientific_id, project_id) values (7, 88);
insert into Concerns (scientific_id, project_id) values (2, 89);
insert into Concerns (scientific_id, project_id) values (6, 90);
insert into Concerns (scientific_id, project_id) values (5, 91);
insert into Concerns (scientific_id, project_id) values (2, 85);
insert into Concerns (scientific_id, project_id) values (9, 88);
insert into Concerns (scientific_id, project_id) values (5, 90);
insert into Concerns (scientific_id, project_id) values (5, 84);
insert into Concerns (scientific_id, project_id) values (4, 86);
insert into Concerns (scientific_id, project_id) values (2, 71);
insert into Concerns (scientific_id, project_id) values (2, 72);
insert into Concerns (scientific_id, project_id) values (5, 73);
insert into Concerns (scientific_id, project_id) values (2, 74);
insert into Concerns (scientific_id, project_id) values (2, 75);
insert into Concerns (scientific_id, project_id) values (5, 76);
insert into Concerns (scientific_id, project_id) values (8, 77);
insert into Concerns (scientific_id, project_id) values (7, 78);
insert into Concerns (scientific_id, project_id) values (2, 79);
insert into Concerns (scientific_id, project_id) values (6, 80);
insert into Concerns (scientific_id, project_id) values (5, 81);
insert into Concerns (scientific_id, project_id) values (6, 75);
insert into Concerns (scientific_id, project_id) values (9, 78);
insert into Concerns (scientific_id, project_id) values (5, 80);
insert into Concerns (scientific_id, project_id) values (5, 74);
insert into Concerns (scientific_id, project_id) values (4, 76);


insert into Works_on (researcher_id, project_id) values (1, 1);
insert into Works_on (researcher_id, project_id) values (2, 1);
insert into Works_on (researcher_id, project_id) values (2, 2);
insert into Works_on (researcher_id, project_id) values (4, 2);
insert into Works_on (researcher_id, project_id) values (5, 3);
insert into Works_on (researcher_id, project_id) values (6, 3);
insert into Works_on (researcher_id, project_id) values (7, 4);
insert into Works_on (researcher_id, project_id) values (6, 4);
insert into Works_on (researcher_id, project_id) values (8, 5);
insert into Works_on (researcher_id, project_id) values (9, 5);
insert into Works_on (researcher_id, project_id) values (11, 6);
insert into Works_on (researcher_id, project_id) values (12, 6);
insert into Works_on (researcher_id, project_id) values (13, 6);
insert into Works_on (researcher_id, project_id) values (12, 7);
insert into Works_on (researcher_id, project_id) values (14, 7);
insert into Works_on (researcher_id, project_id) values (15, 7);
insert into Works_on (researcher_id, project_id) values (11, 8);
insert into Works_on (researcher_id, project_id) values (16, 8);
insert into Works_on (researcher_id, project_id) values (15, 8);
insert into Works_on (researcher_id, project_id) values (17, 9);
insert into Works_on (researcher_id, project_id) values (18, 10);
insert into Works_on (researcher_id, project_id) values (19, 10);
insert into Works_on (researcher_id, project_id) values (19, 11);
insert into Works_on (researcher_id, project_id) values (20, 11);
insert into Works_on (researcher_id, project_id) values (21, 12);
insert into Works_on (researcher_id, project_id) values (21, 13);
insert into Works_on (researcher_id, project_id) values (22, 12);
insert into Works_on (researcher_id, project_id) values (23, 13);
insert into Works_on (researcher_id, project_id) values (24, 14);
insert into Works_on (researcher_id, project_id) values (25, 14);
insert into Works_on (researcher_id, project_id) values (26, 15);
insert into Works_on (researcher_id, project_id) values (27, 16);
insert into Works_on (researcher_id, project_id) values (27, 17);
insert into Works_on (researcher_id, project_id) values (28, 16);
insert into Works_on (researcher_id, project_id) values (28, 17);
insert into Works_on (researcher_id, project_id) values (31, 18);
insert into Works_on (researcher_id, project_id) values (32, 19);
insert into Works_on (researcher_id, project_id) values (33, 19);
insert into Works_on (researcher_id, project_id) values (33, 20);
insert into Works_on (researcher_id, project_id) values (35, 20);
insert into Works_on (researcher_id, project_id) values (37, 21);
insert into Works_on (researcher_id, project_id) values (38, 21);
insert into Works_on (researcher_id, project_id) values (40, 22);
insert into Works_on (researcher_id, project_id) values (39, 22);
insert into Works_on (researcher_id, project_id) values (42, 23);
insert into Works_on (researcher_id, project_id) values (43, 23);
insert into Works_on (researcher_id, project_id) values (44, 23);
insert into Works_on (researcher_id, project_id) values (45, 23);
insert into Works_on (researcher_id, project_id) values (42, 24);
insert into Works_on (researcher_id, project_id) values (44, 24);
insert into Works_on (researcher_id, project_id) values (46, 24);
insert into Works_on (researcher_id, project_id) values (43, 25);
insert into Works_on (researcher_id, project_id) values (45, 25);
insert into Works_on (researcher_id, project_id) values (47, 25);
insert into Works_on (researcher_id, project_id) values (49, 26);
insert into Works_on (researcher_id, project_id) values (50, 26);
insert into Works_on (researcher_id, project_id) values (49, 27);
insert into Works_on (researcher_id, project_id) values (51, 27);
insert into Works_on (researcher_id, project_id) values (52, 28);
insert into Works_on (researcher_id, project_id) values (53, 28);
insert into Works_on (researcher_id, project_id) values (54, 28);
insert into Works_on (researcher_id, project_id) values (53, 29);
insert into Works_on (researcher_id, project_id) values (54, 29);
insert into Works_on (researcher_id, project_id) values (56, 30);
insert into Works_on (researcher_id, project_id) values (57, 31);
insert into Works_on (researcher_id, project_id) values (60, 32);
insert into Works_on (researcher_id, project_id) values (62, 33);
insert into Works_on (researcher_id, project_id) values (63, 33);
insert into Works_on (researcher_id, project_id) values (64, 34);
insert into Works_on (researcher_id, project_id) values (65, 34);
insert into Works_on (researcher_id, project_id) values (63, 34);
insert into Works_on (researcher_id, project_id) values (67, 35);
insert into Works_on (researcher_id, project_id) values (68, 35);
insert into Works_on (researcher_id, project_id) values (69, 35);
insert into Works_on (researcher_id, project_id) values (66, 36);
insert into Works_on (researcher_id, project_id) values (68, 36);
insert into Works_on (researcher_id, project_id) values (69, 36);
insert into Works_on (researcher_id, project_id) values (71, 37);
insert into Works_on (researcher_id, project_id) values (67, 37);
insert into Works_on (researcher_id, project_id) values (72, 38);
insert into Works_on (researcher_id, project_id) values (73, 38);
insert into Works_on (researcher_id, project_id) values (74, 38);
insert into Works_on (researcher_id, project_id) values (72, 39);
insert into Works_on (researcher_id, project_id) values (73, 39);
insert into Works_on (researcher_id, project_id) values (76, 40);
insert into Works_on (researcher_id, project_id) values (80, 41);
insert into Works_on (researcher_id, project_id) values (82, 41); 
insert into Works_on (researcher_id, project_id) values (83, 41);
insert into Works_on (researcher_id, project_id) values (79, 42);
insert into Works_on (researcher_id, project_id) values (78, 42);
insert into Works_on (researcher_id, project_id) values (79, 43);
insert into Works_on (researcher_id, project_id) values (81, 43);
insert into Works_on (researcher_id, project_id) values (80, 43);
insert into Works_on (researcher_id, project_id) values (84, 44);
insert into Works_on (researcher_id, project_id) values (86, 44);
insert into Works_on (researcher_id, project_id) values (88, 45);
insert into Works_on (researcher_id, project_id) values (89, 45);
insert into Works_on (researcher_id, project_id) values (89, 46);
insert into Works_on (researcher_id, project_id) values (90, 46);
insert into Works_on (researcher_id, project_id) values (91, 47);
insert into Works_on (researcher_id, project_id) values (93, 47);
insert into Works_on (researcher_id, project_id) values (94, 47);
insert into Works_on (researcher_id, project_id) values (97, 48);
insert into Works_on (researcher_id, project_id) values (95, 48);
insert into Works_on (researcher_id, project_id) values (99, 49);
insert into Works_on (researcher_id, project_id) values (98, 49);
insert into Works_on (researcher_id, project_id) values (100, 50);
insert into Works_on (researcher_id, project_id) values (99, 50);
insert into Works_on (researcher_id, project_id) values (98, 50);
insert into Works_on (researcher_id, project_id) values (101, 35);
insert into Works_on (researcher_id, project_id) values (101, 36);
insert into Works_on (researcher_id, project_id) values (95, 51);
insert into Works_on (researcher_id, project_id) values (96, 51);
insert into Works_on (researcher_id, project_id) values (97, 52);
insert into Works_on (researcher_id, project_id) values (95, 52);
insert into Works_on (researcher_id, project_id) values (96, 53);
insert into Works_on (researcher_id, project_id) values (97, 53);
insert into Works_on (researcher_id, project_id) values (95, 54);
insert into Works_on (researcher_id, project_id) values (96, 54);
insert into Works_on (researcher_id, project_id) values (97, 55);
insert into Works_on (researcher_id, project_id) values (96, 55);
insert into Works_on (researcher_id, project_id) values (95, 56);
insert into Works_on (researcher_id, project_id) values (97, 56);
insert into Works_on (researcher_id, project_id) values (95, 57);
insert into Works_on (researcher_id, project_id) values (96, 57);
insert into Works_on (researcher_id, project_id) values (97, 58);
insert into Works_on (researcher_id, project_id) values (95, 58);
insert into Works_on (researcher_id, project_id) values (96, 59);
insert into Works_on (researcher_id, project_id) values (97, 59);
insert into Works_on (researcher_id, project_id) values (95, 60);
insert into Works_on (researcher_id, project_id) values (96, 60);
insert into Works_on (researcher_id, project_id) values (99, 61);
insert into Works_on (researcher_id, project_id) values (98, 61);
insert into Works_on (researcher_id, project_id) values (99, 62);
insert into Works_on (researcher_id, project_id) values (98, 62);
insert into Works_on (researcher_id, project_id) values (99, 63);
insert into Works_on (researcher_id, project_id) values (98, 63);
insert into Works_on (researcher_id, project_id) values (99, 64);
insert into Works_on (researcher_id, project_id) values (98, 64);
insert into Works_on (researcher_id, project_id) values (99, 65);
insert into Works_on (researcher_id, project_id) values (100, 65);
insert into Works_on (researcher_id, project_id) values (100, 66);
insert into Works_on (researcher_id, project_id) values (98, 66);
insert into Works_on (researcher_id, project_id) values (99, 67);
insert into Works_on (researcher_id, project_id) values (100, 67);
insert into Works_on (researcher_id, project_id) values (100, 68);
insert into Works_on (researcher_id, project_id) values (98, 68);
insert into Works_on (researcher_id, project_id) values (99, 69);
insert into Works_on (researcher_id, project_id) values (100, 69);
insert into Works_on (researcher_id, project_id) values (100, 70);
insert into Works_on (researcher_id, project_id) values (98, 70);
insert into Works_on (researcher_id, project_id) values (102, 71);
insert into Works_on (researcher_id, project_id) values (103, 71);
insert into Works_on (researcher_id, project_id) values (104, 71);
insert into Works_on (researcher_id, project_id) values (102, 72);
insert into Works_on (researcher_id, project_id) values (103, 72);
insert into Works_on (researcher_id, project_id) values (104, 73);
insert into Works_on (researcher_id, project_id) values (102, 73);
insert into Works_on (researcher_id, project_id) values (103, 74);
insert into Works_on (researcher_id, project_id) values (104, 75);
insert into Works_on (researcher_id, project_id) values (102, 76);
insert into Works_on (researcher_id, project_id) values (103, 77);
insert into Works_on (researcher_id, project_id) values (104, 78);
insert into Works_on (researcher_id, project_id) values (102, 79);
insert into Works_on (researcher_id, project_id) values (103, 80);
insert into Works_on (researcher_id, project_id) values (104, 81);
insert into Works_on (researcher_id, project_id) values (102, 80);
insert into Works_on (researcher_id, project_id) values (103, 79);
insert into Works_on (researcher_id, project_id) values (103, 78);
insert into Works_on (researcher_id, project_id) values (102, 77);
insert into Works_on (researcher_id, project_id) values (103, 76);
insert into Works_on (researcher_id, project_id) values (102, 75);
insert into Works_on (researcher_id, project_id) values (105, 91);
insert into Works_on (researcher_id, project_id) values (106, 91);
insert into Works_on (researcher_id, project_id) values (107, 91);
insert into Works_on (researcher_id, project_id) values (105, 82);
insert into Works_on (researcher_id, project_id) values (106, 82);
insert into Works_on (researcher_id, project_id) values (107, 83);
insert into Works_on (researcher_id, project_id) values (105, 83);
insert into Works_on (researcher_id, project_id) values (106, 84);
insert into Works_on (researcher_id, project_id) values (107, 85);
insert into Works_on (researcher_id, project_id) values (105, 86);
insert into Works_on (researcher_id, project_id) values (106, 87);
insert into Works_on (researcher_id, project_id) values (107, 88);
insert into Works_on (researcher_id, project_id) values (105, 89);
insert into Works_on (researcher_id, project_id) values (106, 90);
insert into Works_on (researcher_id, project_id) values (107, 82);
insert into Works_on (researcher_id, project_id) values (105, 84);
insert into Works_on (researcher_id, project_id) values (106, 89);